version: "3.9"
services:
  code-server:
    image: code-server:latest
    entrypoint: /config/sync.sh && /code-server.sh
    ports:
      - 8080:8080
    volumes:
      - config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
  ngrok:
    image: ngrok/ngrok:alpine
    entrypoint: /config/sync.sh && ngrok start --all
    network_mode: host
    volumes:
      - config:/config
    env_file:
      - ./.env
volumes:
  config:
    external: true
