name: build

on: [push]

jobs:
  build-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: mkdir ./bin
      - run: find ./target/release -type f -maxdepth 1 -executable -exec cp {} ./bin \;
      - uses: actions/upload-artifact@v3
        with:
          name: bin
          path: ./bin

  build-and-push-images:
    uses: mikojs/actions/.github/workflows/build-docker.yml@main
    needs: build-bin
    strategy:
      matrix:
        name: [base, code-server, act]
    with:
      name: ${{ matrix.name }}
      cache_name: bin
      cache_path: ./docker-images/bin
      context: ./docker-images
      file: ./docker-images/${{ matrix.name }}/Dockerfile
      push: ${{ github.ref == 'refs/heads/main' }}

  final-check:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - uses: actions/checkout@v3
