name: build
on: [push]
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build images
        run: |
          docker compose \
            -f ./docker-compose/build.yml
            --project-directory .
            build
