name: build
on: [push]
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build images
        run: |
          if [[ ! -d config ]]; then
            mkdir config
          fi

          for file in $(ls); do
            if [[ -f $file/Dockerfile ]]; then
              echo "[$file] start"
              mkdir config/$file
              docker build -t $file -f ./$file/Dockerfile .
              echo "[$file] end"
            fi
          done
