name: build
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    container: bats/bats
    steps:
      - run: apk add git
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: bats ./test
  build-and-push-images:
    runs-on: ubuntu-latest
    needs: testing
    strategy:
      matrix:
        include:
          - image: mikojs/act
            context: ./act
          - image: mikojs/code-server
            context: ./code-server
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image }}
      - uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
