name: build
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./test/bats/bin/bats ./test
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build images
        run: |
          cd docker-compose
          docker compose \
            -f build.yml \
            build
