name: build
on: [push]
env:
  REGISTRY: ghcr.io/mikojs
jobs:
  build-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: mkdir ./bin
      - run: find ./target/release -type f -maxdepth 1 -executable -exec cp {} ./bin \;
      - uses: actions/upload-artifact@v3
        with:
          name: bin
          path: ./bin

  build-and-push-images:
    uses: ./.github/workflows/build-docker.yml
    needs: build-bin
    strategy:
      matrix:
        - name: base
          context: ./docker-images
          file: ./docker-images/base/Dockerfile
        - name: code-server
          context: ./docker-images
          file: ./docker-images/code-server/Dockerfile
        - name: act
          context: ./docker-images
          file: ./docker-images/act/Dockerfile
    with:
      name: ${{ matrix.name }}
      cache_name: bin
      cache_path: ./docker-images/bin
      context: ${{ matrix.context }}
      file: ${{ matrix.file }}
      push: ${{ github.ref == 'refs/heads/main' }}

  finial-check:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - uses: actions/checkout@v3
