name: build

on: [push]

jobs:
  build-rust:
    uses: mikojs/actions/.github/workflows/build-rust.yml@main
    with:
      name: bin

  build-docker:
    uses: mikojs/actions/.github/workflows/build-docker.yml@main
    needs: build-rust
    strategy:
      matrix:
        name: [base, code-server, act, rust, docker]
    with:
      cache: bin.tar
      name: mikojs/${{ matrix.name }}
      context: ./docker-images/${{ matrix.name }}
      push: ${{ github.ref == 'refs/heads/main' }}

  final-check:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v3
