name: build
on: [push]
env:
  REGISTRY: ghcr.io
jobs:
  build-dind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          working-directory: dind
      - run: cd ./dind && yarn
      - run: |
          yarn --cwd ./dind build
          yarn --cwd ./dind pkg .

  build-and-push-images:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - image: mikojs/code-server
            file: ./code-server/Dockerfile
          - image: mikojs/act
            file: ./act/Dockerfile
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image }}
      - uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: ${{ matrix.file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
