name: build
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    container: bats/bats
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: bats ./test
  build-images:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v3
      - name: build images
        run: |
          cd docker-compose
          docker compose \
            -f build.yml \
            build
